services:
  - type: web
    name: gov-financials-web
    env: node
    plan: starter
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        sync: false
      - key: APP_URL
        sync: false
      - key: SESSION_SECRET
        sync: false

databases:
  - name: gov-financials-db
    plan: starter
